version: "3"

services:
  zookeeper1:
    image: zookeeper:3.4.9
    restart: always
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper:3.4.9
    restart: always
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper:3.4.9
    restart: always
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  kafka1:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - 9092:9092
    container_name: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.3
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - 9093:9092
    container_name: kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.3
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
