version: "3"

services:
  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/
    volumes:
      - ./data:/data
